webpage/transformers/urls.py
from django.urls import path
from . import views

app_name = 'transformers'

urlpatterns = [
    path('', views.main, name='main'),
    path('singleview/', views.singleview, name='Single View'),
]

webpage/webpage/urls.py
from django.contrib import admin
from django.urls import path, include
from transformers import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('transformers/', include('transformers.urls'))
]

webpage/transformers/models.py
from django.db import models


# Create your models here.
class Transformer(models.Model):
    transf_loc = models.CharField(max_length=20)
    sku = models.PositiveIntegerField()
    primary_voltage = models.CharField(max_length=20)
    size_kva = models.CharField(max_length=20, null=True)
    transformer_age = models.CharField(max_length=20, null=True)
    customers = models.CharField(max_length=20, null=True)
    percent_lol = models.CharField(max_length=20, null=True)
    consecutive_months_overloaded = models.CharField(max_length=20, null=True)
    loss_of_life = models.CharField(max_length=20, null=True)
    max_overload = models.CharField(max_length=20, null=True)
    life_expectancy_at_conditions = models.CharField(max_length=20, null=True)
    date_max_overload = models.CharField(max_length=20, null=True)
    loading_flags = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.transf_loc

webpage/transformers/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')


def main(request):
    title = 'Main Page'

    return render(request,
                  'transformers/main.html',
                  {'title': title})


def singleview(request):
    singleview = {
        'Transformer_Loc': 'T 8181',  # Put your name here
        'SKU': '91350',  # Put your country here
    }
    context = {'Transformer Loc': singleview,
               'title': 'Single Transformer View'}

    return render(request,
                  'transformers/user_info.html',
                  context)

webpage/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- INSERT ADDITIONAL INFORMATION TO THE HEAD TAG HERE-->
    {% block head %}
    {% endblock%}

    <!-- CHANGES THE PAGE TITLE IF THE VARIABLE "title" IS PASSED BY THE VIEW -->
    {% if title %}
        <title>{{title}}</title>
    {% else %}
    <!-- USE DEFAULT TITLE TEXT IF NO VARIABLE "title" IS PASSED BY THE VIEW -->
        <title>My Transformers App</title>
    {% endif %}

  </head>
  <body>
    <!-- BOOTSTRAP NAVBAR CODE -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="d-flex justify-content-between px-5 mx-auto" style="width: 90%;">
            <span class="navbar-text text-white">Transformer Data</span>
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'home' %}">Monthly History</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'transformers:main' %}">Yearly Report</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link active" href="{% url 'transformers:Single View' %}">Single Transformer View</a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- END OF NAVBAR CODE-->


    <div class="container-fluid mt-5" style="max-width: 80%">
    <!-- INSERT THE CONTENT FROM SPECIFIC PAGES HERE-->
        {% block content %}
        {% endblock  %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

webpage/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>Monthly History</h1>
<br>
<h3>Search by transf_loc</h3>
<br>
<p>transf_loc: T 10054</p>
<ul>
  <li>2019-01: 0</li>
  <li>2019-02: 0</li>
  <li>2019-03: 0</li>
</ul>
{% endblock  %}

webpage/transformers/templates/transformers/main.html
{% extends 'base.html' %}
{% block content %}
<h1>Transformer Yearly Report</h1>
<br>
<h4>Transformers:</h4>
<ul>
  {% for number in '012'|make_list %}
    <li>TE 86{{forloop.counter}}</li>
  {% endfor %}
</ul>
{% endblock  %}

webpage/transformers/templates/transformers/user_info.html
{% extends 'base.html' %}
{% block content %}
<h1>Single Transformer View</h1>
<br>
{% if singleview %}
  <h4>Transformer Loc: {{singleview.Transformer_Loc}}</h4>
  <h4>SKU: {{single_view.SKU}}</h4>
{% else %}
  <h4>Transformer Loc: N/A</h4>
  <h4>SKU: N/A</h4>
{% endif %}
{% endblock  %}